### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wollanup** [aviggiano/guitar-pro-6#1]
First, thank you for your work Guitar Pro 6 
I am able to run the container, activate Guitar Pro with my license  but application crashes right after, here is the console output :
```
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

RtMidiOut::initialize: error creating ALSA sequencer client object.

terminate called after throwing an instance of 'rtmidi::RtError'
```

I usually use docker for web apps development, I'm not very familiar with running app and use sound in docker. I will try to resolve issue by myself but maybe you have idea.

**Comment by aviggiano** [comment]
Hello @wollanup, thanks for trying this out.

To be honest I had the same issue, and eventually gave up because I had no idea of how to make the container interact with the OS drivers (sound card) properly.

I started this container because I use a linux x64 and didn't want to mess up with my packages by installing 32-bit binaries. 

In the end I started playing my music sheets on this web app: https://flat.io

Anyway, if you figure out how to fix this issue, please let me know :slightly_smiling_face:

**Comment by wollanup** [comment]
OK I can launch guitar pro if I add `--device /dev/snd` in the run command. 
Then I had issue with GPUpdater, because when I launch it guitar pro closes, which stops container, so I tried to run a `tail` command to get container always started. I succesfully updated guitar pro and RSE (sound bank).
But now I'm stuck when I want to play a score, no sound, and playing cursor indication doesn't move.
There is no error, I don't have any time to go further, I will try flat but I need to convert my gpx files to mid or xml.
Here is my run command :
```
docker run -it \
    --name guitarpro \
    --hostname guitarpro \
    --env="DISPLAY" \
    --volume="/home/$USER:/home/$USER:rw" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --device /dev/snd \
    aviggiano/guitar-pro-6 \
    tail -f /dev/null
```
And when container is started :
```
docker exec -it guitarpro /opt/GuitarPro6/launcher.sh
```
Maybe you will have more chance with it !

**Comment by aviggiano** [comment]
Thanks, I'll see if I can make it work and get back to you.

**Comment by JR-Utily** [comment]
I had the same issue, the problem of the "no sound / no cursor" is that it doesn't have a pulse audio server to send its data.

it can be solved by adding 
`ENV PULSE_SERVER /run/pulse/native` in the Dockerfile then by adding a volume `-v /run/user/1000/pulse:/run/pulse:ro ` in the run (1000 is my own userID in my Debian, you should check your own to find the right /run/user/USERID/pulse)

**Comment by JR-Utily** [comment]
The work around I gave you was included in the last version
