### ISSUE TITLE
No sound on Fedora 

### ISSUE THREAD

**Issue by loicdescotte** [aviggiano/guitar-pro-6#4]
Hi, 

Thanks a lot for your great work with this docker image!

I'm using Fedora 30, I've followed all the steps with the master branch version, everything runs fine but I can't hear any sound at all, with or without RSE.
I've checked all the path used in the -v options and all seem ok : 

```
[loic@DESKTOP-NHBSDTK guitar-pro-6]$ ll /dev/snd
total 0
drwxr-xr-x  2 root root       60 12 juil. 08:12 by-path
crw-rw----+ 1 root audio 116, 11 12 juil. 08:12 controlC0
crw-rw----+ 1 root audio 116,  9 12 juil. 08:12 hwC0D0
crw-rw----+ 1 root audio 116, 10 12 juil. 08:12 hwC0D2
crw-rw----+ 1 root audio 116,  3 12 juil. 08:13 pcmC0D0c
crw-rw----+ 1 root audio 116,  2 12 juil. 08:13 pcmC0D0p
crw-rw----+ 1 root audio 116,  8 12 juil. 08:13 pcmC0D10p
crw-rw----+ 1 root audio 116,  4 12 juil. 08:13 pcmC0D3p
crw-rw----+ 1 root audio 116,  5 12 juil. 08:13 pcmC0D7p
crw-rw----+ 1 root audio 116,  6 12 juil. 08:13 pcmC0D8p
crw-rw----+ 1 root audio 116,  7 12 juil. 08:13 pcmC0D9p
crw-rw----+ 1 root audio 116,  1 12 juil. 08:12 seq
crw-rw----+ 1 root audio 116, 33 12 juil. 08:12 timer
[loic@DESKTOP-NHBSDTK guitar-pro-6]$ USER_UID=$(id -u)
[loic@DESKTOP-NHBSDTK guitar-pro-6]$ ll /run/user/$USER_UID/pulse
total 4
srwxrwxrwx 1 loic loic 0 12 juil. 08:13 native
-rw------- 1 loic loic 5 12 juil. 08:13 pid
```

In the audio settings in GP6, I can see that the pulseaudio sound card is detected.

Do you have any idea of what could go wrong? Would it work better with an other distribution, on what distribution do you use this docker image?

Thanks :)

**Comment by JR-Utily** [comment]
Hi !

I personnaly use it with both Ubuntu and Debian without problems. I never used Fedora or other rpm based distro, so I will not be able to test it for you.

Did you succeed in running other docker container with sound (e.g. audacity ) ? 
Jessie Fraz have a lot of examples in her github: 
https://blog.jessfraz.com/post/docker-containers-on-the-desktop/
https://github.com/jessfraz/dockerfiles

**Comment by JR-Utily** [comment]
You can try to install pavucontrol in the container, and then "test" the sound in it, too
In another project, I had a problem with that, only root had the pulse audio device, and the "user" did not.
But if I recall well, there is only a root user in this project.

**Comment by aviggiano** [comment]
Same here, I haven't been able to test this image in other distros other than Ubuntu :slightly_frowning_face:

**Comment by loicdescotte** [comment]
Thanks, 
I'll try on Ubuntu then :)
